platform :ios, '10.0'

def core_pods
    # https://github.com/ReactiveX/RxSwift
    # Reactive Programming in Swift
    pod 'RxSwift'

    # https://github.com/ReactiveX/RxSwift/tree/master/RxCocoa
    # It is a library wrapped in Cocoa Sdk as Rx.
    pod 'RxCocoa'
end

def archi_pods
    # https://github.com/ReactorKit/ReactorKit
    pod 'ReactorKit'
end

def lint_pods
    # Swift style and conventions
    pod 'SwiftLint'
end

def generate_pods
    # https://github.com/SwiftGen/SwiftGen
    # SwiftGen is a tool to auto-generate Swift code for resources of your projects, to make them type-safe to use
    pod 'SwiftGen'
end

def debugging_pods
    # For debugging
    pod 'FLEX', :configurations => ['Debug']
end


target 'RxSwiftReactorKitSampleApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    # core library
    core_pods

    # architecture library
    archi_pods

    # coding style
    lint_pods

    # code generate
    generate_pods

    # debugging library
    debugging_pods
end
